package model;

// Generated 12 avr. 2012 04:38:19 by Hibernate Tools 3.4.0.CR1

/**
 * Copy generated by hbm2java
 */
public class Copy implements java.io.Serializable {

	private Integer idCopy;
	private TypeCopy typeCopy;
	private User user;
	private Record record;
	private String condition;

	public Copy() {
	}

	public Copy(TypeCopy typeCopy, User user, Record record, String condition) {
		this.typeCopy = typeCopy;
		this.user = user;
		this.record = record;
		this.condition = condition;
	}

	public Integer getIdCopy() {
		return this.idCopy;
	}

	public void setIdCopy(Integer idCopy) {
		this.idCopy = idCopy;
	}

	public TypeCopy getTypeCopy() {
		return this.typeCopy;
	}

	public void setTypeCopy(TypeCopy typeCopy) {
		this.typeCopy = typeCopy;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Record getRecord() {
		return this.record;
	}

	public void setRecord(Record record) {
		this.record = record;
	}

	public String getCondition() {
		return this.condition;
	}

	public void setCondition(String condition) {
		this.condition = condition;
	}

}
