package model;

// Generated 12 avr. 2012 14:23:42 by Hibernate Tools 3.4.0.CR1

/**
 * Copy generated by hbm2java
 */
public class Copy implements java.io.Serializable {

	private Integer idCopy;
	private CopyCondition copyCondition;
	private TypeCopy typeCopy;
	private User user;
	private Record record;

	public Copy() {
	}

	public Copy(CopyCondition copyCondition, TypeCopy typeCopy, User user,
			Record record) {
		this.copyCondition = copyCondition;
		this.typeCopy = typeCopy;
		this.user = user;
		this.record = record;
	}

	public Integer getIdCopy() {
		return this.idCopy;
	}

	public void setIdCopy(Integer idCopy) {
		this.idCopy = idCopy;
	}

	public CopyCondition getCopyCondition() {
		return this.copyCondition;
	}

	public void setCopyCondition(CopyCondition copyCondition) {
		this.copyCondition = copyCondition;
	}

	public TypeCopy getTypeCopy() {
		return this.typeCopy;
	}

	public void setTypeCopy(TypeCopy typeCopy) {
		this.typeCopy = typeCopy;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Record getRecord() {
		return this.record;
	}

	public void setRecord(Record record) {
		this.record = record;
	}

}
