package model;

// Generated 13 avr. 2012 18:31:48 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Copy generated by hbm2java
 */
public class Copy implements java.io.Serializable {

	private Integer idCopy;
	private CopyCondition copyCondition;
	private TypeCopy typeCopy;
	private User user;
	private Record record;
	private Set<Playlist> playlists = new HashSet<Playlist>(0);

	public Copy() {
	}

	public Copy(CopyCondition copyCondition, TypeCopy typeCopy, User user,
			Record record) {
		this.copyCondition = copyCondition;
		this.typeCopy = typeCopy;
		this.user = user;
		this.record = record;
	}

	public Copy(CopyCondition copyCondition, TypeCopy typeCopy, User user,
			Record record, Set<Playlist> playlists) {
		this.copyCondition = copyCondition;
		this.typeCopy = typeCopy;
		this.user = user;
		this.record = record;
		this.playlists = playlists;
	}

	public Integer getIdCopy() {
		return this.idCopy;
	}

	public void setIdCopy(Integer idCopy) {
		this.idCopy = idCopy;
	}

	public CopyCondition getCopyCondition() {
		return this.copyCondition;
	}

	public void setCopyCondition(CopyCondition copyCondition) {
		this.copyCondition = copyCondition;
	}

	public TypeCopy getTypeCopy() {
		return this.typeCopy;
	}

	public void setTypeCopy(TypeCopy typeCopy) {
		this.typeCopy = typeCopy;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Record getRecord() {
		return this.record;
	}

	public void setRecord(Record record) {
		this.record = record;
	}

	public Set<Playlist> getPlaylists() {
		return this.playlists;
	}

	public void setPlaylists(Set<Playlist> playlists) {
		this.playlists = playlists;
	}

}
