package model;

// Generated 12 avr. 2012 14:23:42 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * CopyCondition generated by hbm2java
 */
public class CopyCondition implements java.io.Serializable {

	private Integer idCondition;
	private String name;
	private Set<Copy> copies = new HashSet<Copy>(0);

	public CopyCondition() {
	}

	public CopyCondition(String name) {
		this.name = name;
	}

	public CopyCondition(String name, Set<Copy> copies) {
		this.name = name;
		this.copies = copies;
	}

	public Integer getIdCondition() {
		return this.idCondition;
	}

	public void setIdCondition(Integer idCondition) {
		this.idCondition = idCondition;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set<Copy> getCopies() {
		return this.copies;
	}

	public void setCopies(Set<Copy> copies) {
		this.copies = copies;
	}

}
