package model;

// Generated 12 avr. 2012 03:43:20 by Hibernate Tools 3.4.0.CR1

/**
 * LinkCopyRecordId generated by hbm2java
 */
public class LinkCopyRecordId implements java.io.Serializable {

	private int idCopy;
	private int idRecord;

	public LinkCopyRecordId() {
	}

	public LinkCopyRecordId(int idCopy, int idRecord) {
		this.idCopy = idCopy;
		this.idRecord = idRecord;
	}

	public int getIdCopy() {
		return this.idCopy;
	}

	public void setIdCopy(int idCopy) {
		this.idCopy = idCopy;
	}

	public int getIdRecord() {
		return this.idRecord;
	}

	public void setIdRecord(int idRecord) {
		this.idRecord = idRecord;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LinkCopyRecordId))
			return false;
		LinkCopyRecordId castOther = (LinkCopyRecordId) other;

		return (this.getIdCopy() == castOther.getIdCopy())
				&& (this.getIdRecord() == castOther.getIdRecord());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdCopy();
		result = 37 * result + this.getIdRecord();
		return result;
	}

}
