package model;

// Generated 12 avr. 2012 14:23:42 by Hibernate Tools 3.4.0.CR1

/**
 * LinkRecordPerson generated by hbm2java
 */
public class LinkRecordPerson implements java.io.Serializable {

	private LinkRecordPersonId id;
	private RecordRole recordRole;
	private Person person;
	private Record record;

	public LinkRecordPerson() {
	}

	public LinkRecordPerson(LinkRecordPersonId id, RecordRole recordRole,
			Person person, Record record) {
		this.id = id;
		this.recordRole = recordRole;
		this.person = person;
		this.record = record;
	}

	public LinkRecordPersonId getId() {
		return this.id;
	}

	public void setId(LinkRecordPersonId id) {
		this.id = id;
	}

	public RecordRole getRecordRole() {
		return this.recordRole;
	}

	public void setRecordRole(RecordRole recordRole) {
		this.recordRole = recordRole;
	}

	public Person getPerson() {
		return this.person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

	public Record getRecord() {
		return this.record;
	}

	public void setRecord(Record record) {
		this.record = record;
	}

}
