package model;

// Generated 12 avr. 2012 03:43:20 by Hibernate Tools 3.4.0.CR1

/**
 * LinkRecordPersonId generated by hbm2java
 */
public class LinkRecordPersonId implements java.io.Serializable {

	private int idRecord;
	private int idPerson;
	private int idRecordRole;

	public LinkRecordPersonId() {
	}

	public LinkRecordPersonId(int idRecord, int idPerson, int idRecordRole) {
		this.idRecord = idRecord;
		this.idPerson = idPerson;
		this.idRecordRole = idRecordRole;
	}

	public int getIdRecord() {
		return this.idRecord;
	}

	public void setIdRecord(int idRecord) {
		this.idRecord = idRecord;
	}

	public int getIdPerson() {
		return this.idPerson;
	}

	public void setIdPerson(int idPerson) {
		this.idPerson = idPerson;
	}

	public int getIdRecordRole() {
		return this.idRecordRole;
	}

	public void setIdRecordRole(int idRecordRole) {
		this.idRecordRole = idRecordRole;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LinkRecordPersonId))
			return false;
		LinkRecordPersonId castOther = (LinkRecordPersonId) other;

		return (this.getIdRecord() == castOther.getIdRecord())
				&& (this.getIdPerson() == castOther.getIdPerson())
				&& (this.getIdRecordRole() == castOther.getIdRecordRole());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdRecord();
		result = 37 * result + this.getIdPerson();
		result = 37 * result + this.getIdRecordRole();
		return result;
	}

}
