package model;

// Generated 12 avr. 2012 04:38:19 by Hibernate Tools 3.4.0.CR1

/**
 * LinkCopyRecord generated by hbm2java
 */
public class LinkCopyRecord implements java.io.Serializable {

	private LinkCopyRecordId id;

	public LinkCopyRecord() {
	}

	public LinkCopyRecord(LinkCopyRecordId id) {
		this.id = id;
	}

	public LinkCopyRecordId getId() {
		return this.id;
	}

	public void setId(LinkCopyRecordId id) {
		this.id = id;
	}

}
