package model;

// Generated 13 avr. 2012 18:31:48 by Hibernate Tools 3.4.0.CR1

/**
 * PlaylistWorkerId generated by hbm2java
 */
public class PlaylistWorkerId implements java.io.Serializable {

	private int idPlaylist;
	private int idUser;
	private int idRight;

	public PlaylistWorkerId() {
	}

	public PlaylistWorkerId(int idPlaylist, int idUser, int idRight) {
		this.idPlaylist = idPlaylist;
		this.idUser = idUser;
		this.idRight = idRight;
	}

	public int getIdPlaylist() {
		return this.idPlaylist;
	}

	public void setIdPlaylist(int idPlaylist) {
		this.idPlaylist = idPlaylist;
	}

	public int getIdUser() {
		return this.idUser;
	}

	public void setIdUser(int idUser) {
		this.idUser = idUser;
	}

	public int getIdRight() {
		return this.idRight;
	}

	public void setIdRight(int idRight) {
		this.idRight = idRight;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PlaylistWorkerId))
			return false;
		PlaylistWorkerId castOther = (PlaylistWorkerId) other;

		return (this.getIdPlaylist() == castOther.getIdPlaylist())
				&& (this.getIdUser() == castOther.getIdUser())
				&& (this.getIdRight() == castOther.getIdRight());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdPlaylist();
		result = 37 * result + this.getIdUser();
		result = 37 * result + this.getIdRight();
		return result;
	}

}
