package model;

// Generated 13 avr. 2012 18:31:48 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Playlist generated by hbm2java
 */
public class Playlist implements java.io.Serializable {

	private Integer idPlaylist;
	private User user;
	private String name;
	private Set<Copy> copies = new HashSet<Copy>(0);
	private Set<PlaylistWorker> playlistWorkers = new HashSet<PlaylistWorker>(0);

	public Playlist() {
	}

	public Playlist(User user, String name) {
		this.user = user;
		this.name = name;
	}

	public Playlist(User user, String name, Set<Copy> copies,
			Set<PlaylistWorker> playlistWorkers) {
		this.user = user;
		this.name = name;
		this.copies = copies;
		this.playlistWorkers = playlistWorkers;
	}

	public Integer getIdPlaylist() {
		return this.idPlaylist;
	}

	public void setIdPlaylist(Integer idPlaylist) {
		this.idPlaylist = idPlaylist;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set<Copy> getCopies() {
		return this.copies;
	}

	public void setCopies(Set<Copy> copies) {
		this.copies = copies;
	}

	public Set<PlaylistWorker> getPlaylistWorkers() {
		return this.playlistWorkers;
	}

	public void setPlaylistWorkers(Set<PlaylistWorker> playlistWorkers) {
		this.playlistWorkers = playlistWorkers;
	}

}
