package model;

// Generated 8 avr. 2012 19:54:58 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * RecordLibrary generated by hbm2java
 */
public class RecordLibrary implements java.io.Serializable {

	private Integer idRecordLibrary;
	private User user;
	private int name;
	private Set<Copy> copies = new HashSet<Copy>(0);

	public RecordLibrary() {
	}

	public RecordLibrary(User user, int name) {
		this.user = user;
		this.name = name;
	}

	public RecordLibrary(User user, int name, Set<Copy> copies) {
		this.user = user;
		this.name = name;
		this.copies = copies;
	}

	public Integer getIdRecordLibrary() {
		return this.idRecordLibrary;
	}

	public void setIdRecordLibrary(Integer idRecordLibrary) {
		this.idRecordLibrary = idRecordLibrary;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public int getName() {
		return this.name;
	}

	public void setName(int name) {
		this.name = name;
	}

	public Set<Copy> getCopies() {
		return this.copies;
	}

	public void setCopies(Set<Copy> copies) {
		this.copies = copies;
	}

}
