package model;

// Generated 13 avr. 2012 18:31:48 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Right generated by hbm2java
 */
public class Right implements java.io.Serializable {

	private Integer idRight;
	private String name;
	private Set<PlaylistWorker> playlistWorkers = new HashSet<PlaylistWorker>(0);

	public Right() {
	}

	public Right(String name) {
		this.name = name;
	}

	public Right(String name, Set<PlaylistWorker> playlistWorkers) {
		this.name = name;
		this.playlistWorkers = playlistWorkers;
	}

	public Integer getIdRight() {
		return this.idRight;
	}

	public void setIdRight(Integer idRight) {
		this.idRight = idRight;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set<PlaylistWorker> getPlaylistWorkers() {
		return this.playlistWorkers;
	}

	public void setPlaylistWorkers(Set<PlaylistWorker> playlistWorkers) {
		this.playlistWorkers = playlistWorkers;
	}

}
