package model;

// Generated 12 avr. 2012 20:44:23 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Track generated by hbm2java
 */
public class Track implements java.io.Serializable {

	private Integer idTrack;
	private Style style;
	private String title;
	private String rythm;
	private String originalVersion;
	private int label;
	private int playingTime;
	private Date releaseDate;
	private Set<Record> records = new HashSet<Record>(0);
	private Set<Person> persons = new HashSet<Person>(0);

	public Track() {
	}

	public Track(Style style, String title, String rythm,
			String originalVersion, int label, int playingTime, Date releaseDate) {
		this.style = style;
		this.title = title;
		this.rythm = rythm;
		this.originalVersion = originalVersion;
		this.label = label;
		this.playingTime = playingTime;
		this.releaseDate = releaseDate;
	}

	public Track(Style style, String title, String rythm,
			String originalVersion, int label, int playingTime,
			Date releaseDate, Set<Record> records, Set<Person> persons) {
		this.style = style;
		this.title = title;
		this.rythm = rythm;
		this.originalVersion = originalVersion;
		this.label = label;
		this.playingTime = playingTime;
		this.releaseDate = releaseDate;
		this.records = records;
		this.persons = persons;
	}

	public Integer getIdTrack() {
		return this.idTrack;
	}

	public void setIdTrack(Integer idTrack) {
		this.idTrack = idTrack;
	}

	public Style getStyle() {
		return this.style;
	}

	public void setStyle(Style style) {
		this.style = style;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getRythm() {
		return this.rythm;
	}

	public void setRythm(String rythm) {
		this.rythm = rythm;
	}

	public String getOriginalVersion() {
		return this.originalVersion;
	}

	public void setOriginalVersion(String originalVersion) {
		this.originalVersion = originalVersion;
	}

	public int getLabel() {
		return this.label;
	}

	public void setLabel(int label) {
		this.label = label;
	}

	public int getPlayingTime() {
		return this.playingTime;
	}

	public void setPlayingTime(int playingTime) {
		this.playingTime = playingTime;
	}

	public Date getReleaseDate() {
		return this.releaseDate;
	}

	public void setReleaseDate(Date releaseDate) {
		this.releaseDate = releaseDate;
	}

	public Set<Record> getRecords() {
		return this.records;
	}

	public void setRecords(Set<Record> records) {
		this.records = records;
	}

	public Set<Person> getPersons() {
		return this.persons;
	}

	public void setPersons(Set<Person> persons) {
		this.persons = persons;
	}

}
