package model;

// Generated 13 avr. 2012 15:26:32 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TypeCopy generated by hbm2java
 */
public class TypeCopy implements java.io.Serializable {

	private Integer idTypeCopy;
	private String name;
	private Set<Copy> copies = new HashSet<Copy>(0);

	public TypeCopy() {
	}

	public TypeCopy(String name) {
		this.name = name;
	}

	public TypeCopy(String name, Set<Copy> copies) {
		this.name = name;
		this.copies = copies;
	}

	public Integer getIdTypeCopy() {
		return this.idTypeCopy;
	}

	public void setIdTypeCopy(Integer idTypeCopy) {
		this.idTypeCopy = idTypeCopy;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set<Copy> getCopies() {
		return this.copies;
	}

	public void setCopies(Set<Copy> copies) {
		this.copies = copies;
	}

}
