package model;

// Generated 13 avr. 2012 18:31:48 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer idUser;
	private Language language;
	private String username;
	private boolean admin;
	private String password;
	private String emailAdress;
	private String firstname;
	private String lastname;
	private String biography;
	private String picture;
	private String website;
	private String socialNetworkAccount;
	private Set<Playlist> playlists = new HashSet<Playlist>(0);
	private Set<Record> records = new HashSet<Record>(0);
	private Set<PlaylistWorker> playlistWorkers = new HashSet<PlaylistWorker>(0);
	private Set<Copy> copies = new HashSet<Copy>(0);

	public User() {
	}

	public User(Language language, String username, boolean admin,
			String password, String emailAdress, String firstname,
			String lastname, String biography, String picture, String website,
			String socialNetworkAccount) {
		this.language = language;
		this.username = username;
		this.admin = admin;
		this.password = password;
		this.emailAdress = emailAdress;
		this.firstname = firstname;
		this.lastname = lastname;
		this.biography = biography;
		this.picture = picture;
		this.website = website;
		this.socialNetworkAccount = socialNetworkAccount;
	}

	public User(Language language, String username, boolean admin,
			String password, String emailAdress, String firstname,
			String lastname, String biography, String picture, String website,
			String socialNetworkAccount, Set<Playlist> playlists,
			Set<Record> records, Set<PlaylistWorker> playlistWorkers,
			Set<Copy> copies) {
		this.language = language;
		this.username = username;
		this.admin = admin;
		this.password = password;
		this.emailAdress = emailAdress;
		this.firstname = firstname;
		this.lastname = lastname;
		this.biography = biography;
		this.picture = picture;
		this.website = website;
		this.socialNetworkAccount = socialNetworkAccount;
		this.playlists = playlists;
		this.records = records;
		this.playlistWorkers = playlistWorkers;
		this.copies = copies;
	}

	public Integer getIdUser() {
		return this.idUser;
	}

	public void setIdUser(Integer idUser) {
		this.idUser = idUser;
	}

	public Language getLanguage() {
		return this.language;
	}

	public void setLanguage(Language language) {
		this.language = language;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public boolean isAdmin() {
		return this.admin;
	}

	public void setAdmin(boolean admin) {
		this.admin = admin;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getEmailAdress() {
		return this.emailAdress;
	}

	public void setEmailAdress(String emailAdress) {
		this.emailAdress = emailAdress;
	}

	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	public String getBiography() {
		return this.biography;
	}

	public void setBiography(String biography) {
		this.biography = biography;
	}

	public String getPicture() {
		return this.picture;
	}

	public void setPicture(String picture) {
		this.picture = picture;
	}

	public String getWebsite() {
		return this.website;
	}

	public void setWebsite(String website) {
		this.website = website;
	}

	public String getSocialNetworkAccount() {
		return this.socialNetworkAccount;
	}

	public void setSocialNetworkAccount(String socialNetworkAccount) {
		this.socialNetworkAccount = socialNetworkAccount;
	}

	public Set<Playlist> getPlaylists() {
		return this.playlists;
	}

	public void setPlaylists(Set<Playlist> playlists) {
		this.playlists = playlists;
	}

	public Set<Record> getRecords() {
		return this.records;
	}

	public void setRecords(Set<Record> records) {
		this.records = records;
	}

	public Set<PlaylistWorker> getPlaylistWorkers() {
		return this.playlistWorkers;
	}

	public void setPlaylistWorkers(Set<PlaylistWorker> playlistWorkers) {
		this.playlistWorkers = playlistWorkers;
	}

	public Set<Copy> getCopies() {
		return this.copies;
	}

	public void setCopies(Set<Copy> copies) {
		this.copies = copies;
	}

}
